# Runs Bazel tests for DeepMind Lab

os: osx

env:
  - BUILD_TYPE=osmesa

language: c++

addons:
  homebrew:
    taps:
      - bazelbuild/tap
      - homebrew/cask-versions
    casks:
      - java8

before_install:
  - brew install bazel glib sdl2

script:
  - bazel build -c opt --copt=-Wno-sign-compare --show_progress_rate_limit=10 //:game
